/* By YZBruh */

/**
 * Copyright 2024 Partition Manager
 *
 * Licensed under the Apache License, Version 2.0 (the "License";
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *	 http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#define INC_MAIN_LIBS 1
#define INC_STRINGKEYS 1

#include <PartitionManager/PartitionManager.h>

namespace PartitionManager {
namespace Display {

struct langdb_general LangEn = {
	.lang_by_s = "YZBruh & r0manas",
	.language = "English",
	.lang_prefix = "en",
	.not_logical = "This device does not have logical partitions!",
	.not_file = "is not a file.",
	.not_dir = "is not a directory.",
	.not_in_dev = "Nothing found in /dev. Use force mode to avoid this error.",
	.not_open = "Couldn't open",
	.not_block = "The specified partition is not recognized as a block device. Use force mode to avoid this error.",
	.not_read = "Couldn't read",
	.not_readdir = "Couldn't read directory",
	.not_write = "Couldn't write",
	.not_gen = "Couldn't generate",
	.no_root = "Root access could not be detected! Please run this with root permissions.",
	.expected_backup_arg = "Expected backup argument 2 (1 of them are not mandatory), retrieved",
	.expected_flash_arg = "Expected flash argument 2, retrieved",
	.expected_format_arg = "Expected format argument 2, retrieved",
	.expected_partsz_arg = "Expected partition-size argument 1, retrieved",
	.expected_partutil_arg = "Expected part-util argument 1, retrieved",
	.missing_operand = "Missing operand",
	.multiple_wiewers = "Multiple viewers can't be used on the same line.",
	.symbol_rule = "When specifying arguments for an option, ensure they do not begin with '-'. Each argument must correspond correctly to its respective option.",
	.req_part_name = "Partition name required.",
	.part_not_found = "Partition not found! Maybe a logical partition?",
	.unsupported_fs = "Formatter: unsupported filesystem",
	.cannot_stat = "Cannot stat",
	.ffile_more_part = "Flash file size exceeds partition capacity. Use force mode to avoid this error (not recommended, riscy!).",
	.cannot_get_bsz = "Failed to retrieve partition block size.",
	.format_fail = "Formatting failed! There is a possibility of data damage.",
	.fail_get_psize = "Cannot get partition size",
	.depr_backup_opt = "These options for the backup are unavailable.",
	.depr_flash_opt = "These options for the flash are unavailable.",
	.depr_format_opt = "These options for the format are unavailable.",
	.depr_Vlicense_opt = "Deprecated because it was unnecessary.",
	.depr_ch_list_opt = "Use -p argument for listing partitions.",
	.depr_ch_sp_opt = "Use -P (--search-path) argument instead of -c (--context).",
	.not_spec_opt = "Specify the necessary arguments, not option",
	.some_spec = "You may have indicated options, but they don't work much unless you speficy a main transaction",
	.logical_warn = "This device uses logical partitions.",
	.ab_warn = "This device uses A/B partition style.",
	.out_not_spec = "Output file name not specified. Using created name",
	.no_found_on_process = "The file that was processed was not found. Something wen wrong...",
	.please_rerun = "Please rerun the command.",
	.part_disk_sz = "Partition (backup) size",
	.flash_file_sz = "Flash file size",
	.part_disk_sz_fail = "Failed to retrieve partition disk size.",
	.flash_file_sz_fail = "Failed to retrieve flash file size.",
	.cannot_find_any_defdevice = "Couldn't find any default device",
	.cannot_find_device = "Device not founded",
	.found_defdevice = "Founded a default device",
	.not_spec_device_on_args = "Device is not speficed in arguments. Searching default devices (by pmt)",
	.starting_parted = "Starting parted",
	.exited_with = "Exited parted with exit code",
	.unknown_opr = "Unknown operand",
	.req_an_arg = "option requires an argument",
	.list_of_general = "List of general partitions",
	.list_of_logc = "List of logical partitions",
	.success_backup = "Backup successful. Output",
	.success_flash = "Flash successful",
	.success_format = "Format successful",
	.formatting = "Formatting",
	.warn = "WARNING",
	.fatal = "FATAL ERROR",
	.is_requires_arg = "requires an argument",
	.only_partsz_args = "Flags can be used only in partition size view were identified. But target not this",
	.unknw_arg = "unknown option",
	.switching_lang = "Switching language...",
	.welcome = "language!",
	.welcome_ = "Welcome to ",
	.for_more = "for more information",
	.s_and_v = "Silent and verbose mode cannot be used together!",
	.try_h = "Try",
	.usage_head = "Usage",
	.depr_opt_str = "DEPRECATED OPTION",
	.switched_opt_str = "SWITCHED OPTION",
	.not_changed_opt = "not changed",
	.compiler_str = "compiler",
	.version_str = "version",
	.bin_str = "binary",
	.part_name = "Partition name",
	.part_type = "Partition is dynamic",
	.fs_str = "Filesystem",
	.unknw_str = "unknown",
	.by_str = "By",
	.yes = "true",
	.no = "false"
};

struct langdb_general LangTr = {
	.lang_by_s = "YZBruh",
	.language = "Türkçe",
	.lang_prefix = "tr",
	.not_logical = "Bu cihaz mantıksal (logical) bölümlere sahip değil!",
	.not_file = "Bu bir dosya değil",
	.not_dir = "Bu bir dizin değil",
	.not_in_dev = "Bu bir şakamı? Bunun /dev dizini ile bir ilgisi yok (içermiyor). Bu hatayla karşılaşmak istemiyorsanız zorlama (force) modu kullanın.",
	.not_open = "Açılamıyor",
	.not_block = "Belirtilen bölüm bir blok değil. Yani aslında bu bir bölüm bile değil (disk). Bu hatayı almak için şanslı olmak gerek..! Bu hatayla karşılaşmak istemiyorsanız zorlama (force) modu kullanın.",
	.not_read = "Veri okunamıyor",
	.not_readdir = "Dizin verisi okunamıyor",
	.not_write = "Veri yazılamıyor",
	.not_gen = "Oluşturulamıyor",
	.no_root = "Root erişimi tespit edilemedi! Lütfen root erişimi ile çalıştırın.",
	.expected_backup_arg = "Beklenen yedekleme argümanı 2 (bir tanesi zorunlu değil), alınan",
	.expected_flash_arg = "Beklenen flaş argümanı 2, alınan",
	.expected_format_arg = "Beklenen format argümanı 2, alınan",
	.expected_partsz_arg = "Beklenen partition-size argümanı 1, alınan",
	.expected_partutil_arg = "Beklenen part-util argümanı 1, alınan",
	.missing_operand = "İşlem belirtilmedi",
	.multiple_wiewers = "Birden fazla görüntüleme işlemi yapan fonksiyonlar bir arada kullanılamaz. Aynı anda sadece bir tanesi kullanılabilir.",
	.symbol_rule = "Bir seçeneğin argümanını verirken argüman önüne '-' sembolü getirilemez. Sembolü kaldırın ve tekrar deneyin.",
	.req_part_name = "Bölüm adı gereklidir.",
	.part_not_found = "Bölüm bulunamadı! Belki mantıksal (logical) bir bölümdür?",
	.unsupported_fs = "Formatlayıcı: desteklenmeyen dosya sistemi:",
	.cannot_stat = "Durumu tespit edilemedi",
	.ffile_more_part = "Flaşlanacak dosyanın boyutu mevcut bölüm boyutundan fazla. Bu hatayla karşılaşmak istemiyorsanız zorlama (force) modu kullanın (bunu yapmanız asla önerilmez).",
	.cannot_get_bsz = "Bölüm blok boyutu tespit edilemedi!",
	.format_fail = "Formatlama başarısız oldu. Bazı şeyler zarar görmüş olabilir!",
	.fail_get_psize = "Bölüm boyutu alınamadı",
	.depr_backup_opt = "Yedek için artık bu seçeneği kullanamazsınız.",
	.depr_flash_opt = "Flaşlama için artık bu seçeneği kullanamazsınız.",
	.depr_format_opt = "Formatlama için artıi bu seçeneği kullanamazsınız.",
	.depr_Vlicense_opt = "Gereksiz seçeneklere bellek yok!",
	.depr_ch_list_opt = "Listeleme için -p seçeneğini kullanabilirsiniz.",
	.depr_ch_sp_opt = "Özel arama dizini belirtmek için -P (--search-path) seçeneğini kullanabilirsiniz.",
	.logical_warn = "Bu cihaz mantıksal (logical) bölümlere sahip.",
	.not_spec_opt = "Seçenek değil, şuan gerekli argümanları verin",
	.some_spec = "Seçenek belirtmiş olabilirsiniz fakat, ana işlem belirtmedikçe pek işe yaramazlar",
	.ab_warn = "Bu cihazın bazı bölümleri A/B kullanıyor.",
	.out_not_spec = "Çıktı dosya adı belirtilmedi. Oluşturulan çıktı adı",
	.no_found_on_process = "İşlenmekte olan dosya bulunamadı. Bir şeyler yanlış...",
	.please_rerun = "Lütfen yeniden çalıştırın",
	.part_disk_sz = "Bölümün (yedek) boyutu",
	.flash_file_sz = "Flaşlanacak dosyanın boyutu",
	.flash_file_sz_fail = "Uyarı: flaşlanacak dosyanın boyutu tespit edilemedi.",
	.part_disk_sz_fail = "Uyarı: bölüm boyutunun boyutu tespit edilemedi.",
	.found_defdevice = "Varsayılan bir cihaz bulundu",
	.cannot_find_any_defdevice = "Herhangi bir varsayılan cihaz bulunamadı",
	.cannot_find_device = "Cihaz bulunamadı",
	.not_spec_device_on_args = "Cihaz argümanlarda belirtilmedi. Varsayılan cihazlar aranıyor (pmt tarafından tanımlanan cihazlar)",
	.starting_parted = "Parted başlatılıyor",
	.exited_with = "Parted çıkış kodu",
	.unknown_opr = "Bilinmeyen işlem",
	.req_an_arg = "bu seçenek argüman gerektirir",
	.list_of_general = "Genel bölümlerin listesi",
	.list_of_logc = "Mantıksal (logical) bölümlerin listesi",
	.success_backup = "Başarılı. Çıktı",
	.success_flash = "Başarılı.",
	.success_format = "Formatlama başarılı",
	.formatting = "Formatlanıyor",
	.warn = "UYARI",
	.fatal = "KRİTİK HATA",
	.is_requires_arg = "bir argüman gereklidir",
	.only_partsz_args = "Sadece bölüm boyutu görüntülemesinde kullanılabilecek bayraklar tespit edildi. Ama hedef bu değil",
	.unknw_arg = "bilinmeyen seçenek",
	.switching_lang = "Dil değiştiriliyor...",
	.welcome = "diline hoş geldiniz!",
	.welcome_ = NULL,
	.for_more = "komutunu kullanabilirsiniz",
	.s_and_v = "Sessiz ve ayrıntılı günlüklenme aynı anda kullanılamaz!",
	.try_h = "Daha fazla bilgi",
	.usage_head = "Kullanımı",
	.depr_opt_str = "KALDIRILMIŞ SEÇENEK",
	.switched_opt_str = "DEĞİŞTİRİLMİŞ SEÇENEK",
	.not_changed_opt = "değiştirilmedi",
	.compiler_str = "derleyicisi",
	.version_str = "versiyon",
	.bin_str = "yapı",
	.part_name = "Bölüm adı",
	.part_type = "Dinamik bölüm",
	.fs_str = "Dosya sistemi",
	.unknw_str = "bilinmeyen",
	.by_str = "Çeviriyi yapan(lar):",
	.yes = "evet",
	.no = "hayır"
};

struct langdb_docs LangDocEn = {
	.docs_strs_l1 = "[OPTIONS] start-parted [DEVICE]...",
	.docs_strs_l2 = "[OPTIONS] backup PARTITION [OUTPUT] [OPTIONS]...",
	.docs_strs_l3 = "[OPTIONS] flash PARTITION FILE [OPTIONS]...",
	.docs_strs_l4 = "[OPTIONS] format PARTITION FILE_SYSTEM[ext/2/3/4] [OPTIONS]...",
	.docs_strs_l5 = "[OPTIONS] partition-size PARTITION [OPTIONS]...",
	.docs_strs_l6 = "Options",
	.docs_strs_l7 = "It is meant to determine whether the target partition is logical.",
	.docs_strs_l8 = "It is meant to specify a custom partition search path. Only normal partitions (default: /dev/block/by-name).",
	.docs_strs_l9 = "List partitions.",
	.docs_strs_l10 = "Information and warning messages are silenced in normal work.",
	.docs_strs_l11 = "Force mode. Some things are ignored.",
	.docs_strs_l12 = "Verbose mode. Print detailed informations etc.",
	.docs_strs_l13 = "Set current language.",
	.docs_strs_l14 = "See version.",
	.docs_strs_l15 = "See this help message.",
	.docs_strs_l16 = "partition-size flags",
	.docs_strs_l17 = "Only the size is displayed, the partition name etc is not displayed.",
	.docs_strs_l18 = "Display size as byte.",
	.docs_strs_l19 = "Display size as kilobyte.",
	.docs_strs_l20 = "Display size as megabyte.",
	.docs_strs_l21 = "Display size as gigabyte.",
	.docs_strs_l22 = "Examples",
	.docs_strs_l23 = "Report bugs and suggestions to",
	.or_str = "or",
	.usage_docstr = "Usage"
};

struct langdb_docs LangDocTr = {
	.docs_strs_l1 = "[SEÇENEKLER] start-parted [CİHAZ]...",
	.docs_strs_l2 = "[SEÇENEKLER] backup BÖLÜM [ÇIKTI] [SEÇENEKLER]...",
	.docs_strs_l3 = "[SEÇENEKLER] flash BÖLÜM DOSYA [SEÇENEKLER]...",
	.docs_strs_l4 = "[SEÇENEKLER] format BÖLÜM DOSYA_SİSTEMİ[ext/2/3/4] [SEÇENEKLER]...",
	.docs_strs_l5 = "[SEÇENEKLER] partition-size BÖLÜM [SEÇENEKLER]...",
	.docs_strs_l6 = "Seçenekler",
	.docs_strs_l7 = "Mantıksal (logical) bölüm ile işlem yapın.",
	.docs_strs_l8 = "Özel bir bölüm arama dizini belirtin. Sadece normal bölümler içindir (Varsayılan: /dev/block/by-name).",
	.docs_strs_l9 = "Bölümler listelenir.",
	.docs_strs_l10 = "Bilgi ve uyarı mesajları susturulur.",
	.docs_strs_l11 = "Zorlama modu. Bazı şeyler göz ardı edilir.",
	.docs_strs_l12 = "Ayrıntılı bilgi modu. Daha fazla bilgi mesajı verilir.",
	.docs_strs_l13 = "Mevcut dili ayarlayın.",
	.docs_strs_l14 = "Sürümü görüntüleyin.",
	.docs_strs_l15 = "Bu yardım mesajını görüntüleyin.",
	.docs_strs_l16 = "partition-size bayrakları",
	.docs_strs_l17 = "Boyut görüntülenirken bölüm adı vb gibi bilgiler verilmez, sadece boyut görüntülenir.",
	.docs_strs_l18 = "Boyutu bayt olarak görüntüleyin.",
	.docs_strs_l19 = "Boyutu kilobayt olarak görüntüleyin.",
	.docs_strs_l20 = "Boyutu megabyte olarak görüntüleyin.",
	.docs_strs_l21 = "Boyutu gigabayt olarak görüntüleyin.",
	.docs_strs_l22 = "Örnekler",
	.docs_strs_l23 = "Sorunları ve önerileri şuraya bildirin:",
	.or_str = "yada",
	.usage_docstr = "Kullanımı"
};

} /* namespace Display */
} /* namespace PartitionManager */

/* end of code */
